### ISSUE TITLE
brackets in variable names

### ISSUE THREAD

**Issue by lucasart** [zamar/spsa#4]
With Marco's tune branch, `TUNE(array)` will generate variables names containing `[` and `]` characters.

This code throws an error:
```
die "Invalid name: '$row->[$VAR_NAME]'" if ($row->[$VAR_NAME] !~ /^\w+$/);
```
Instead, replace with:
```
die "Invalid name: '$row->[$VAR_NAME]'" if ($row->[$VAR_NAME] !~ /^[\w\[\]]+$/);
```
and it works.

**Comment by zamar** [comment]
Merged.
